                                                                <!doctype html>
  <head>
    <title>Social Media Tweets</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel="stylesheet" href="tweetstyles.css">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600,700' rel='stylesheet' type='text/css'>
  </head>
  <body>
<div id="twittersection">
    

 

                            
                            
                            